### ISSUE TITLE
Hunger getting replenished even without the armor

### ISSUE THREAD

**Issue by masmasmas66** [Xipit/apple-armor#5]
or any other armor.

**Comment by Xipit** [comment]
Hi, can you give me more detail on your setup?
Which Apple Armor version where you using and did this happen randomly or the entire time? Did you have any other mods installed?

**Comment by masmasmas66** [comment]
I only have the apple armor 1.2.0
and the latest qfapi 
also happens the entire time
[latest.log](https://github.com/Xipit/apple-armor/files/9678089/latest.log)

**Comment by Xipit** [comment]
Are you on 1.18.2 or 1.19.2?
Have you tested with a different version of the Quilted Fabric API?

Since this bug doesnt appear on the normal fabric API this seems more like a bug on their (Quilt) end. 
I will try to recreate the bug when i have time, but i cant guarentee you that i will be able to fix it since Apple Armor is strictly a fabric mod.

**Comment by masmasmas66** [comment]
I'm on 1.19.2
And no i didn't
It's understandable if you can't fix it thanks for taking a look anyway,
i guess it always happened independent of qfapi version, i would have to check.
